# Generated by Django 3.2 on 2022-08-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20220801_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галлерея', 'verbose_name_plural': 'Галлерея'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='captions',
            field=models.TextField(blank=True, max_length=250, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(to='gallery.Photo', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Мини-тег'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='captions',
            field=models.TextField(blank=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Мини-тег'),
        ),
    ]
