# Generated by Django 3.2 on 2022-08-12 15:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20220801_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Страница About', 'verbose_name_plural': 'Страница About'},
        ),
        migrations.AlterModelOptions(
            name='contactlink',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локация'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Контакты пользователей', 'verbose_name_plural': 'Контакты пользователей'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Социальные ссылки', 'verbose_name_plural': 'Социальные ссылки'},
        ),
        migrations.AlterField(
            model_name='about',
            name='mini_text',
            field=ckeditor.fields.RichTextField(verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='icon',
            field=models.FileField(upload_to='icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Вебсайт'),
        ),
        migrations.AlterField(
            model_name='imageabout',
            name='alt',
            field=models.CharField(max_length=100, verbose_name='Мини-тег'),
        ),
        migrations.AlterField(
            model_name='imageabout',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imageabout',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='contact.about', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.FileField(upload_to='icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название ресурса'),
        ),
    ]
